### ISSUE TITLE
Add command matching

### ISSUE THREAD

**Issue by tomjefferys** [tomjefferys/tift#1]
Must be able to specify before/after commands

```yaml
---
object : soup
before:
   - stir($self) => "You burn your hands"
   - stir($self).with(spoon) => "Using the wooden spoon you stir the boiling hot soup"
```

Parser for the match syntax has been created, this now need to be wired in.
