### ISSUE TITLE
Support command matching syntax shortcut

### ISSUE THREAD

**Issue by tomjefferys** [tomjefferys/tift#2]
Consider supporting the following syntax

```yaml
---
object: soup
before:
    stir: "You stir the soup"
``` 

When loaded this would be converted into:
```yaml
object: soup
before:
  - stir($self) => "You stir the soup"
```
